# Generated by Django 3.1.6 on 2021-02-14 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0002_userlearningstyle_completed_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlearningstyle',
            name='user_ls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userlearningstyle', to=settings.AUTH_USER_MODEL),
        ),
    ]
