# Generated by Django 3.1.6 on 2021-02-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210214_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlearningstyle',
            name='act_or_ref',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userlearningstyle',
            name='sen_or_int',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userlearningstyle',
            name='seq_or_glob',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userlearningstyle',
            name='vis_or_verb',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
