# Generated by Django 3.1.6 on 2021-02-25 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0004_auto_20210221_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_no', models.IntegerField()),
                ('score', models.IntegerField()),
                ('user_quizres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcquizresults', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
