# Generated by Django 3.1.6 on 2021-02-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_quizresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='trophy',
            field=models.BooleanField(default=False),
        ),
    ]
