# Generated by Django 3.1.6 on 2021-03-04 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_quizresults_trophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
