# Generated by Django 3.1.6 on 2021-03-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_quizresults_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
