from django.db import models

# Create your models here.
class LearningModuleContent(models.Model):
    module = models.CharField(max_length=100)
    moduleNum = models.IntegerField()
    lessonNum  = models.IntegerField()
    sub_module =  models.TextField( blank=True)
    intro = models.TextField( blank=True)
    active_1_1  = models.TextField( blank=True)
    active_1_2  = models.TextField( blank=True)
    active_2_1 = models.TextField( blank=True)
    active_2_2 = models.TextField( blank=True)
    active_3_1  = models.TextField( blank=True)
    active_3_2 = models.TextField( blank=True)
    reflective_1_1 = models.TextField( blank=True)
    reflective_1_2 = models.TextField( blank=True)
    reflective_2_1 = models.TextField( blank=True)
    reflective_2_2 = models.TextField( blank=True)
    reflective_3_1 = models.TextField( blank=True)
    reflective_3_2 = models.TextField( blank=True)
    visual_1_1 = models.TextField( blank=True)
    visual_1_2 = models.TextField( blank=True)
    visual_2_1 = models.TextField( blank=True)
    visual_2_2 = models.TextField( blank=True)
    visual_3_1 = models.TextField( blank=True)
    visual_3_2 = models.TextField( blank=True)
    visual_photo_1 = models.ImageField(upload_to='visual_photos', blank=True)
    visual_photo_2 = models.ImageField(upload_to='visual_photos', blank=True)
    visual_photo_3 = models.ImageField(upload_to='visual_photos', blank=True)
    verbal_1_1 = models.TextField( blank=True)
    verbal_1_2 = models.TextField( blank=True)
    verbal_1_3 = models.TextField( blank=True)
    verbal_2_1 = models.TextField( blank=True)
    verbal_2_2 = models.TextField( blank=True)
    verbal_2_3 = models.TextField( blank=True)
    verbal_3_1 = models.TextField( blank=True)
    verbal_3_2 = models.TextField( blank=True)
    verbal_3_3 = models.TextField( blank=True)
    sensing_1 = models.TextField( blank=True)
    sensing_2 = models.TextField( blank=True)
    sensing_3 = models.TextField( blank=True)
    intuitive_1 = models.TextField( blank=True)
    intuitive_2 = models.TextField( blank=True)
    intuitive_3 = models.TextField( blank=True)
    code_example_1 = models.ImageField(upload_to='code_photos', blank=True)
    code_example_2 = models.ImageField(upload_to='code_photos', blank=True)
    code_answer_1 = models.TextField( blank=True)
    code_answer_2 = models.TextField( blank=True)


class LearningStyleQuestionnaire(models.Model):
    question = models.TextField(max_length=1000)
    option_A = models.TextField(max_length=1000)
    option_B = models.TextField(max_length=1000)