# Generated by Django 3.1.6 on 2021-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20210221_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='active_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='active_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='active_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='code_answer_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='code_answer_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='code_example_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='code_example_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='intuitive_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='intuitive_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='intuitive_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='reflective_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='reflective_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='reflective_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='sensing_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='sensing_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='sensing_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='verbal_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='verbal_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='verbal_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='visual_1',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='visual_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='visual_3',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
