# Generated by Django 3.1.6 on 2021-02-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_auto_20210222_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='active_1',
            new_name='active_1_1',
        ),
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='active_2',
            new_name='active_1_2',
        ),
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='active_3',
            new_name='active_2_1',
        ),
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='reflective_1',
            new_name='active_2_2',
        ),
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='reflective_2',
            new_name='active_3_1',
        ),
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='reflective_3',
            new_name='active_3_2',
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='reflective_1_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='reflective_1_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='reflective_2_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='reflective_2_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='reflective_3_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='reflective_3_2',
            field=models.TextField(blank=True),
        ),
    ]
