# Generated by Django 3.1.6 on 2021-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20210222_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodulecontent',
            name='visual_1_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='visual_2_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='visual_3_3',
            field=models.TextField(blank=True),
        ),
    ]
