# Generated by Django 3.1.6 on 2021-02-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_auto_20210224_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodulecontent',
            name='verbal_title_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='verbal_title_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='verbal_title_3',
            field=models.TextField(blank=True),
        ),
    ]
