# Generated by Django 3.1.6 on 2021-02-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_auto_20210224_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('option_A', models.TextField(max_length=1000)),
                ('option_B', models.TextField(max_length=1000)),
                ('option_C', models.TextField(max_length=1000)),
                ('option_D', models.TextField(max_length=1000)),
                ('correct', models.TextField(max_length=1000)),
            ],
        ),
    ]
