# Generated by Django 3.1.6 on 2021-02-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learningstylequestionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModuleContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100, unique=True)),
                ('moduleNum', models.IntegerField()),
                ('lessonNum', models.IntegerField()),
                ('active_1', models.CharField(max_length=1000)),
                ('active_2', models.CharField(max_length=1000)),
                ('active_3', models.CharField(max_length=1000)),
                ('reflective_1', models.CharField(max_length=1000)),
                ('reflective_2', models.CharField(max_length=1000)),
                ('reflective_3', models.CharField(max_length=1000)),
                ('visual_1', models.CharField(max_length=1000)),
                ('visual_2', models.CharField(max_length=1000)),
                ('visual_3', models.CharField(max_length=1000)),
                ('visual_photo_1', models.ImageField(blank=True, upload_to='visual_photos')),
                ('visual_photo_2', models.ImageField(blank=True, upload_to='visual_photos')),
                ('visual_photo_3', models.ImageField(blank=True, upload_to='visual_photos')),
                ('verbal_1', models.CharField(max_length=1000)),
                ('verbal_2', models.CharField(max_length=1000)),
                ('verbal_3', models.CharField(max_length=1000)),
                ('sensing_1', models.CharField(max_length=1000)),
                ('sensing_2', models.CharField(max_length=1000)),
                ('sensing_3', models.CharField(max_length=1000)),
                ('intuitive_1', models.CharField(max_length=1000)),
                ('intuitive_2', models.CharField(max_length=1000)),
                ('intuitive_3', models.CharField(max_length=1000)),
                ('code_example_1', models.CharField(max_length=1000)),
                ('code_example_2', models.CharField(max_length=1000)),
                ('code_answer_1', models.CharField(max_length=1000)),
                ('code_answer_2', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='LearningModule',
        ),
    ]
