# Generated by Django 3.1.6 on 2021-02-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_auto_20210222_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodulecontent',
            name='sub_module',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='code_answer_1',
            field=models.TextField(blank=True),
        ),
    ]
