# Generated by Django 3.1.6 on 2021-02-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_auto_20210222_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='verbal_1',
            new_name='verbal_1_1',
        ),
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='verbal_2',
            new_name='verbal_1_2',
        ),
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='verbal_3',
            new_name='verbal_1_3',
        ),
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='visual_1',
            new_name='verbal_2_1',
        ),
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='visual_2',
            new_name='verbal_2_2',
        ),
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='visual_3',
            new_name='verbal_2_3',
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='verbal_3_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='verbal_3_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='verbal_3_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='visual_1_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='visual_1_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='visual_2_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='visual_2_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='visual_3_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='visual_3_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningmodulecontent',
            name='module',
            field=models.CharField(max_length=100),
        ),
    ]
