# Generated by Django 3.1.6 on 2021-02-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_auto_20210224_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='code_answer_1',
            new_name='code_answer_1_1',
        ),
        migrations.RenameField(
            model_name='learningmodulecontent',
            old_name='code_answer_2',
            new_name='code_answer_1_2',
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='code_answer_2_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='code_answer_2_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='code_answer_3_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningmodulecontent',
            name='code_answer_3_2',
            field=models.TextField(blank=True),
        ),
    ]
