# Generated by Django 3.1.6 on 2021-02-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_auto_20210225_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquiz',
            name='question_1',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
