# Generated by Django 3.1.6 on 2021-02-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_mcquiz_question_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcquiz',
            name='option_A_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mcquiz',
            name='option_B_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mcquiz',
            name='option_C_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mcquiz',
            name='option_D_1',
            field=models.TextField(blank=True),
        ),
    ]
